package com.ns.news.domain.model


enum class ViewType {
    VT_NOT_DEFINED,
//    ARTICLE_VT_NOT_VALID,
//    WIDGET_VT_NOT_VALID,
    ARTICLE_VT_STANDARD,
    ARTICLE_VT_PHOTOS,
    ARTICLE_VT_VIDEO,
    WIDGET_VT_TOP_NEWS_COROUSAL,
    WIDGET_VT_HERO_PLAIN_WIDGET,
    WIDGET_VT_WEB_WIDGET,
    WIDGET_VT_PLAIN_WITH_COROUSAL,
    WIDGET_VT_STACK_CARD_WITH_COROUSAL,
    WIDGET_VT_ALL_TOPICS_WIDGET,
    WIDGET_VT_FOR_YOU_WIDGET,
    WIDGET_VT_GLAMOR_COROUSAL_WIDGET,
    WIDGET_VT_PAGER_GALLERY,
}